version: '3.8'

services:
  # ---------------------------
  # 1. Aplikasi Backend (NestJS)
  # ---------------------------
  app:
    container_name: smartiv-ads-api-${ENV_NAME}
    image: ${APP_IMAGE}
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '${APP_PORT}:3000'
    depends_on:
      - postgres
      - redis
    networks:
      - smartiv-net
      - shared_network

  # ---------------------------
  # 2. Database (PostgreSQL)
  # ---------------------------
  postgres:
    image: postgres:15-alpine
    container_name: smartiv-ads-postgres-${ENV_NAME}
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data_${ENV_NAME}:/var/lib/postgresql/data
    networks:
      - smartiv-net

  # ---------------------------
  # 3. Queue & Cache (Redis)
  # ---------------------------
  redis:
    image: redis:alpine
    container_name: smartiv-ads-redis-${ENV_NAME}
    restart: unless-stopped
    networks:
      - smartiv-net

  # ---------------------------
  # 4. MinIO Bucket Creator (ROBOT PINTAR)
  # ---------------------------
  createbuckets:
    image: minio/mc
    container_name: smartiv-ads-createbuckets-${ENV_NAME}
    env_file:
      - .env
    # Script: Loop checking connection -> Create Bucket -> Set Public Policy
    entrypoint: >
      /bin/sh -c "
      echo '🔍 Config: Host=${MINIO_ENDPOINT}, Port=${MINIO_PORT}, Bucket=${MINIO_BUCKET}';

      # 1. Retry Connection Loop (Sampai MinIO siap)
      until /usr/bin/mc alias set myminio http://${MINIO_ENDPOINT}:${MINIO_PORT} ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY}; do
        echo '⏳ MinIO belum siap... Menunggu 3 detik...';
        sleep 3;
      done;

      echo '✅ MinIO Connected!';

      # 2. Create Bucket (Abaikan jika sudah ada)
      /usr/bin/mc mb --ignore-existing myminio/${MINIO_BUCKET};

      # 3. Set Public Policy (Download Only)
      /usr/bin/mc anonymous set download myminio/${MINIO_BUCKET};

      echo '🎉 SUCCESS: Bucket ${MINIO_BUCKET} is ready & public!';
      exit 0;
      "
    networks:
      - shared_network # Wajib satu network dengan 'minio-server'

# Volume Data
volumes:
  postgres_data_prod:
  postgres_data_staging:

# Network
networks:
  smartiv-net:
    driver: bridge
  shared_network:
    external: true
