version: '3.8'

services:
  # ---------------------------
  # 1. Aplikasi Backend (NestJS)
  # ---------------------------
  app:
    # Nama container dinamis: smartiv-ads-api-prod / smartiv-ads-api-staging
    container_name: smartiv-ads-api-${ENV_NAME}
    image: ${APP_IMAGE}
    restart: unless-stopped
    env_file:
      - .env
    # Port mapping dinamis (Port Luar : Port Dalam)
    # Prod: 3000:3000 | Staging: 3001:3000
    ports:
      - '${APP_PORT}:3000'
    depends_on:
      - postgres
      - redis
    networks:
      - smartiv-net # Network internal app ini (DB & Redis)
      - shared_network # Network luar (Konek ke MinIO & Nginx Proxy Manager)

  # ---------------------------
  # 2. Database (PostgreSQL) - Dedicated per Environment
  # ---------------------------
  postgres:
    image: postgres:15-alpine
    container_name: smartiv-ads-postgres-${ENV_NAME}
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data_${ENV_NAME}:/var/lib/postgresql/data
    networks:
      - smartiv-net

  # ---------------------------
  # 3. Queue & Cache (Redis) - Dedicated per Environment
  # ---------------------------
  redis:
    image: redis:alpine
    container_name: smartiv-ads-redis-${ENV_NAME}
    restart: unless-stopped
    networks:
      - smartiv-net

# Volume Data (Agar data tidak hilang saat restart)
volumes:
  postgres_data_prod:
  postgres_data_staging:

# Konfigurasi Network
networks:
  smartiv-net:
    driver: bridge
  # Network ini WAJIB sudah ada di VPS (milik MinIO/Nginx kamu)
  shared_network:
    external: true
